# Site settings
title: Thoughts
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here are some things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chadwellington.github.io" # the base hostname & protocol for your site
github_username:  chadwellington

# Build settings
markdown: kramdown
